### ISSUE TITLE
couldn't compile testX for EdX

### ISSUE THREAD

**Issue by hosamshahin** [OpenDSA/OpenDSAX#3]
I tried to compile testX for Edx-platform using ``make testXEDX`` but the build process failed.
Here is the log 

    edxapp@precise64:/edx/OpenDSAX$ make testXEDX
    python tools/configure.py --edx config/testX.json
    Configuring OpenDSA, using config/testX.json
     
    Validating config/testX.json
     
    Writing files to /edx/OpenDSAX/Books/testX/
     
    Generating index.rst
     
    Processing...
    Sorting
      Quicksort
    Appendix
      Glossary
      Bibliography
     
    Generating ToDo file...
     
    Building textbook...
    make[1]: Warning: File `Makefile' has modification time 6.1 s in the futuremake[1]: Entering directory `/edx/OpenDSAX/Books/testX'
     
    sphinx-build -b html source oxl/
    Making output directory...
    Running Sphinx v1.1.3
     
    Extension error:
    Could not import extension rst2edx (exception: No module named xml)
    make[1]: *** [html] Error 1
    make[1]: Leaving directory `/edx/OpenDSAX/Books/testX'
    Traceback (most recent call last):
      File "tools/configure.py", line 442, in <module>
        configure(args[0], options)
      File "tools/configure.py", line 416, in configure
        update_TOC(config.book_src_dir, config.book_dir + config.rel_book_output_path, module_chap_map)
      File "/edx/OpenDSAX/tools/postprocessor.py", line 140, in update_TOC
        update_index_html(dest_dir, sectnum)
      File "/edx/OpenDSAX/tools/postprocessor.py", line 51, in update_index_html
        with open(dest_dir + 'index.xml', 'r') as index_html_file:
    IOError: [Errno 2] No such file or directory: u'/edx/OpenDSAX/Books/testX/oxl/index.xml'
    make: *** [testXEDX] Error 1
    edxapp@precise64:/edx/OpenDSAX$

**Comment by acbart** [comment]
I'll take a look at it now!

**Comment by acbart** [comment]
The problem seemed to be an imported module used in the rst2edx builder that I was originally tinkering with. Although my version of docutils had that module, your's may not have. It's an irrelevant problem, however, since the rst2edx builder isn't a necessary part of my build process modifications - all of my work happens in the post-processor. I've removed the rst2edx extension (9aaa1197d553033b65ea6a0a9c79e9489e21d133), and also cleaned out a few of the extraneous print statements that might distract you as you interact with my build process.

This may not be sufficient - I may have missed an import, or may have misdiagnoised. Let me know if there are further issues!
